-- Per-device SoftAP credentials.
-- Generated server-side by claim-device starting with build 2026-05-01+.
-- NULL means the device was claimed before this change shipped — after the
-- firmware OTA its SoftAP becomes open (no password) until the device is
-- factory-reset and re-claimed, at which point a backend-generated password
-- is assigned.

ALTER TABLE embeddeds
  ADD COLUMN IF NOT EXISTS softap_password text;

COMMENT ON COLUMN embeddeds.softap_password IS
  'Per-device SoftAP password generated by claim-device at claim time. NULL for rows created by the pre-2026-05-01 backend; such devices fall back to an open AP.';
